services:
  postgres-test:
    container_name: splitiv-postgres-test
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5433:5432'
    restart: unless-stopped
