services:
  app:
    container_name: splitiv-app
    image: ghcr.io/kdurek/splitiv
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - splitiv
      - proxy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  postgres:
    container_name: splitiv-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - splitiv
    environment:
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pgbackups3:
    container_name: splitiv-pgbackups3
    image: eeshugerman/postgres-backup-s3:15
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - splitiv
    environment:
      - SCHEDULE=0 4 * * *
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=backup
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres:

networks:
  splitiv:
  proxy:
    external: true
