services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

  pgbackups:
    container_name: pgbackups
    image: prodrigestivill/postgres-backup-local
    user: postgres:postgres
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./pgbackups:/backups
    networks:
      - main

volumes:
  postgres:

networks:
  main:
    driver: bridge
