/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthExpensesRouteRouteImport } from './routes/_auth/expenses/route'
import { Route as AuthExpensesIndexRouteImport } from './routes/_auth/expenses/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthExpensesCreateRouteImport } from './routes/_auth/expenses/create'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthExpensesRouteRoute = AuthExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthExpensesIndexRoute = AuthExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthExpensesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExpensesCreateRoute = AuthExpensesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthExpensesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/expenses': typeof AuthExpensesRouteRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/expenses/create': typeof AuthExpensesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/expenses/': typeof AuthExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/settings': typeof AuthSettingsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/expenses/create': typeof AuthExpensesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/expenses': typeof AuthExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/expenses': typeof AuthExpensesRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/expenses/create': typeof AuthExpensesCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/expenses/': typeof AuthExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/settings'
    | '/login'
    | '/signup'
    | '/expenses/create'
    | '/api/auth/$'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/login'
    | '/signup'
    | '/expenses/create'
    | '/api/auth/$'
    | '/expenses'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_auth/expenses'
    | '/_auth/settings'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/'
    | '/_auth/expenses/create'
    | '/api/auth/$'
    | '/_auth/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/expenses': {
      id: '/_auth/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthExpensesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/expenses/': {
      id: '/_auth/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthExpensesIndexRouteImport
      parentRoute: typeof AuthExpensesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/expenses/create': {
      id: '/_auth/expenses/create'
      path: '/create'
      fullPath: '/expenses/create'
      preLoaderRoute: typeof AuthExpensesCreateRouteImport
      parentRoute: typeof AuthExpensesRouteRoute
    }
  }
}

interface AuthExpensesRouteRouteChildren {
  AuthExpensesCreateRoute: typeof AuthExpensesCreateRoute
  AuthExpensesIndexRoute: typeof AuthExpensesIndexRoute
}

const AuthExpensesRouteRouteChildren: AuthExpensesRouteRouteChildren = {
  AuthExpensesCreateRoute: AuthExpensesCreateRoute,
  AuthExpensesIndexRoute: AuthExpensesIndexRoute,
}

const AuthExpensesRouteRouteWithChildren =
  AuthExpensesRouteRoute._addFileChildren(AuthExpensesRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthExpensesRouteRoute: typeof AuthExpensesRouteRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthExpensesRouteRoute: AuthExpensesRouteRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
