name: CI

on:
  push:
    branches: [ main ]

env:
  DATABASE_URL: "https://fake.com"
  NODE_ENV: test
  NEXTAUTH_SECRET: fake
  NEXTAUTH_URL: "https://fake.com"
  GOOGLE_CLIENT_ID: fake
  GOOGLE_CLIENT_SECRET: fake

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /usr/src/splitiv
            docker compose -f docker-compose.production.yml up -d
            docker system prune -f
            docker compose -f docker-compose.production.yml down
            git pull origin main
            pnpm install
            docker compose -f docker-compose.production.yml build --no-cache
            docker compose -f docker-compose.production.yml up -d

